# Generated by Django 3.2.4 on 2021-09-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100, verbose_name='User Name')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('company_logo', models.ImageField(max_length=140, upload_to='', verbose_name='Company Logo')),
                ('role', models.CharField(max_length=50, verbose_name='Company Logo')),
                ('background', models.ImageField(max_length=140, upload_to='', verbose_name='Background')),
                ('generated_background', models.ImageField(blank=True, max_length=140, null=True, upload_to='', verbose_name='Generated Background')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'db_table': 'user_background',
            },
        ),
    ]
