# Generated by Django 3.2.4 on 2021-09-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_backgrounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbackground',
            name='background',
            field=models.CharField(max_length=140, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='userbackground',
            name='role',
            field=models.CharField(max_length=50, verbose_name='Role In Companty'),
        ),
    ]
