# Generated by Django 3.2.4 on 2021-09-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_backgrounds', '0002_auto_20210921_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbackground',
            name='generated_background',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Generated Background'),
        ),
    ]
