# Generated by Django 3.2.4 on 2021-09-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('background_images', '0003_alter_backgroundimage_image'),
        ('user_backgrounds', '0003_alter_userbackground_generated_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbackground',
            name='background',
        ),
        migrations.AddField(
            model_name='userbackground',
            name='background_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_image', to='background_images.backgroundimage'),
        ),
    ]
