# Generated by Django 3.2.4 on 2021-09-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_backgrounds', '0004_auto_20210921_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbackground',
            name='generated_background',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Generated Background'),
        ),
    ]
