# Generated by Django 3.2.4 on 2021-09-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='name',
            field=models.CharField(db_index=True, default='Anonymous', max_length=14, verbose_name='Name'),
        ),
    ]
