# Generated by Django 3.2.4 on 2021-09-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_images', '0003_alter_backgroundimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
